name: Publish to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-pyroscope:
    name: pyroscope-lib
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'lib-')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: publish pyroscope crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
  publish-cli:
    name: pyroscope-cli
    runs-on: ubuntu-latest
    if: "startsWith(github.event.release.tag_name, 'cli-')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: publish pyroscope crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish --manifest-path pyroscope_cli/Cargo.toml
