name: Pre-Release

on: [push]

jobs:
  lib-release:
    name: Create draft release for Main Library
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    continue-on-error: true
    steps:
      - uses: "marvinpinto/action-automatic-releases@v1.1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
  cli-release:
    name: Create draft release for CLI Application
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/cli-')"
    steps:
      - name: install libunwind (for pprof)
        run: sudo apt install libunwind8-dev

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: omarabid-forks/rs-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test & Build
        uses: omarabid-forks/rs-cargo@v1
        with:
          args: --manifest-path pyroscope_cli/Cargo.toml
          command: build
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: "marvinpinto/action-automatic-releases@v1.1.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "latest ${{ github.ref_name }}"
          draft: true
          prerelease: false
